export function getFormStyles(palette, theme) {
  return {
    container: { background: palette.panel, borderRadius: '8px' },
    heading: {
      color: palette.text,
      fontSize: '24px',
      fontWeight: '600',
      marginBottom: '8px',
      letterSpacing: '-0.025em',
    },
    inputContainer: {
      background: palette.muted,
      borderRadius: '6px',
      padding: '16px',
      border: `1px solid ${palette.border}`,
      marginBottom: '16px',
    },
    formCard: {
      color: palette.text,
      background: palette.panel,
      borderRadius: '6px',
      padding: '24px',
      border: `1px solid ${palette.border}`,
    },
    formStack: { gap: '20px' },
    // Ensure multi-column sections in the demo stay in a row
    formGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      gap: '2rem',
      width: '100%',
    },
    fieldContainer: { marginBottom: '20px' },
    fieldLabel: {
      color: theme === 'light' ? palette.text : '#ffffff',
      fontWeight: '500', 
      fontSize: '14px',
      display: 'block',
    },
    input: {
      background: theme === 'light' ? palette.inputBg : '#262626',
      border: `1px solid ${theme === 'light' ? palette.border : '#404040'}`,
      borderRadius: '6px',
      color: theme === 'light' ? palette.inputText : '#ffffff',
      padding: '8px 12px',
      fontSize: '14px',
      width: '100%',
      transition: 'border-color 0.2s ease',
      _focus: {
        borderColor: palette.accent,
        outline: 'none',
        boxShadow: '0 0 0 2px rgba(16, 185, 129, 0.2)',
      },
    },
    textarea: {
      background: theme === 'light' ? palette.inputBg : '#262626',
      border: `1px solid ${theme === 'light' ? palette.border : '#404040'}`,
      borderRadius: '6px',
      color: theme === 'light' ? palette.inputText : '#ffffff',
      padding: '12px',
      fontSize: '14px',
      fontFamily:
        'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
      width: '100%',
      minHeight: '120px',
      transition: 'border-color 0.2s ease',
      _focus: {
        borderColor: palette.accent,
        outline: 'none',
        boxShadow: '0 0 0 2px rgba(16, 185, 129, 0.2)',
      },
    },
    select: {
      background: theme === 'light' ? palette.inputBg : '#1a1a1a',
      border: `1px solid ${theme === 'light' ? palette.border : '#404040'}`,
      borderRadius: '6px',
      color: theme === 'light' ? palette.inputText : '#ffffff',
      fontSize: '14px',
      padding: '12px 40px 12px 12px',
      width: '100%',
      transition: 'border-color 0.2s ease',
      appearance: 'none',
      backgroundImage:
        "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%23a3a3a3' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='m6 8 4 4 4-4'/%3e%3c/svg%3e\")",
      backgroundPosition: 'right 12px center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: '16px',
      _focus: {
        borderColor: palette.accent,
        outline: 'none',
        boxShadow: '0 0 0 2px rgba(16, 185, 129, 0.2)',
      },
    },
    checkbox: { width: '16px', height: '16px', accentColor: palette.accent, marginRight: '8px', flexShrink: 0 },
    label: { cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', color: theme === 'light' ? palette.text : '#ffffff', fontSize: '14px' },
    text: { color: theme === 'light' ? palette.text : '#ffffff', fontSize: '14px' },
    button: {
      background: palette.accent,
      color: 'white',
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      fontWeight: '500',
      border: 'none',
      transition: 'all 0.2s ease',
      _hover: { background: '#059669' },
    },
    secondaryButton: {
      background: 'transparent',
      color: theme === 'light' ? palette.subtext : '#a3a3a3',
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      fontWeight: '500',
      border: `1px solid ${theme === 'light' ? palette.border : '#404040'}`,
      transition: 'all 0.2s ease',
      _hover: { background: palette.muted, borderColor: palette.border, color: palette.text },
    },
    buttonGroup: { justifyContent: 'flex-start', gap: '16px' },
    controlButtons: { justifyContent: 'flex-start', gap: '16px', marginTop: '24px', paddingTop: '16px', borderTop: '1px solid #2d2d2d' },
    saveButton: {
      background: palette.accent,
      color: theme === 'light' ? '#ffffff' : 'white',
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      marginRight: '16px',
      fontWeight: '500',
      border: 'none',
      transition: 'all 0.2s ease',
      _hover: { background: '#059669' },
    },
    cancelButton: {
      background: 'transparent',
      color: palette.danger,
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      fontWeight: '500',
      border: `1px solid ${palette.danger}`,
      transition: 'all 0.2s ease',
      _hover: { background: palette.danger, color: '#ffffff' },
    },
  }
}
